name: Deploy to WP Engine

on:  
  push:
    branches:
      - main
      - stage 
      - dev

env:
  GH_PRODUCTION_BRANCH: main
  WPE_PRODUCTION_ENV: brettkrueger

  GH_STAGING_BRANCH: stage
  WPE_STAGING_ENV: bkruegerstage

  GH_DEVELOPMENT_BRANCH: dev
  WPE_DEVELOPMENT_ENV: bkruegerdev

  WPE_SSHG_KEY_PRIVATE: ${{ secrets.PRIVATE_KEY_NAME }} 
  TPO_SRC_PATH: ""
  TPO_PATH: ""


jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
      - run: echo $GITHUB_REF
      - uses: actions/checkout@v2
        name: GitHub Deploy to WP Engine

      - name: Set variable (prod)
        if: github.ref == "refs/heads/${{ env.GH_PRODUCTION_BRANCH }}"
        run: |
          echo "WPE_ENV_NAME=${{ env.WPE_PRODUCTION_ENV }}" >> $GITHUB_ENV
      - name: Set variable (stage)
        if: endsWith(github.ref, "/${{ env.GH_STAGING_BRANCH }}")
        run: |
          echo "WPE_ENV_NAME=${{ env.WPE_STAGING_ENV }}" >> $GITHUB_ENV
      - name: Set variable (dev)
        if: endsWith(github.ref, "/${{ env.GH_DEVELOPMENT_BRANCH }}")
        run: |
          echo "WPE_ENV_NAME=${{ env.WPE_DEVELOPMENT_ENV }}" >> $GITHUB_ENV

      - uses: brettkrueger/github-action-wpe-site-deploy@feature/brett
    
      - name: Test env variables
        run: echo "$WPE_ENV_NAME"