name: Deploy to WP Engine

on:  
  push:

env:
  PRD_BRANCH: main
  PRD_ENV: brettkrueger

  STG_BRANCH: stage
  STG_ENV: bkruegerstage

  DEV_BRANCH: dev
  DEV_ENV: bkruegerdev

  WPE_SSHG_KEY_PRIVATE: ${{ secrets.PRIVATE_KEY_NAME }} 
  TPO_SRC_PATH: ""
  TPO_PATH: ""

  PHP_LINT: true
  PHP_VER: "7.4"

jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: GitHub Deploy to WP Engine

      - uses: brettkrueger/github-action-wpe-site-deploy@feature/brett