name: Deploy to WP Engine

on:  
  push:

env:
  GH_PRODUCTON_BRANCH: main
  WPE_PRODUCTION_ENV: brettkrueger

  GH_STAGING_BRANCH: stage
  WPE_STAGING_ENV: bkruegerstage

  GH_DEVELOPMENT_BRANCH: dev
  WPE_DEVELOPMENT_ENV: bkruegerdev

  WPE_SSHG_KEY_PRIVATE: ${{ secrets.PRIVATE_KEY_NAME }} 
  TPO_SRC_PATH: ""
  TPO_PATH: ""

jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: GitHub Deploy to WP Engine

      - name: Set variable (prod)
        if: endsWith(github.ref, '/main')
        run: |
          echo "WPE_ENV_NAME=${{ env.WPE_PRODUCTION_ENV }}" >> $GITHUB_ENV
      - name: Set variable (stage)
        if: endsWith(github.ref, '/stage')
        run: |
          echo "WPE_ENV_NAME=${{ env.WPE_STAGING_ENV }}" >> $GITHUB_ENV
      - name: Set variable (dev)    
        if: endsWith(github.ref, '/dev')
        run: |
          echo "WPE_ENV_NAME=${{ env.WPE_DEVELOPMENT_ENV }}" >> $GITHUB_ENV

      - uses: wpengine/github-action-wpe-site-deploy@main

