name: Deploy to WP Engine

on:  
  push:

env:
  GH_PRODUCTON_BRANCH: main
  WPE_PRODUCTION_ENV: brettkrueger

  GH_STAGING_BRANCH: stage
  WPE_STAGING_ENV: bkruegerstage

  GH_DEVELOPMENT_BRANCH: dev
  WPE_DEVELOPMENT_ENV: bkruegerdev

  WPE_SSHG_KEY_PRIVATE: ${{ secrets.PRIVATE_KEY_NAME }} 
  TPO_SRC_PATH: ""
  TPO_PATH: ""

jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: GitHub Deploy to WP Engine
        
      - uses: brettkrueger/github-action-wpe-site-deploy@feature/brett

