name: Deploy to WP Engine
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: brettkrueger/github-action-wpe-site-deploy@feature/brett
      env:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.PRIVATE_KEY_NAME }} 
        PHP_LINT: "TRUE"
        TPO_SRC_PATH: ""
        TPO_PATH: ""
      # Branches & Environments 
        PRD_BRANCH: main
        PRD_ENV: brettkrueger
        STG_BRANCH: stage
        STG_ENV: bkruegerstage
        DEV_BRANCH: dev
        DEV_ENV: bkruegerdev